// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArrayInputController from "./array_input_controller"
application.register("array-input", ArrayInputController)

import MovieTabsController from "./movie_tabs_controller"
application.register("movie-tabs", MovieTabsController)

import SeatsController from "./seats_controller";
application.register("seats", SeatsController)

import ConditionalFieldsController from "./conditional_fields_conlroller";
application.register("conditional-fields", ConditionalFieldsController)
