require:
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
