tmdb:
  api_key: <%= ENV['TMDB_API_KEY'] %>
  api_read_access_token: <%= ENV['TMDB_API_READ_ACCESS_TOKEN'] %>
  url: https://api.themoviedb.org
  img_url: https://image.tmdb.org
  img_path: /t/p/w440_and_h660_face
stripe:
  publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  signing_secret: <%= ENV["STRIPE_SIGNING_SECRET"] %>
